source 'https://rubygems.org'

gem 'activerecord'
gem 'grape'
gem 'grape-rabl'
gem 'grape-swagger'
gem 'pg'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'

group :development, :test do
  gem 'cane'
  gem 'codeclimate-test-reporter'
  gem 'coveralls'
  gem 'database_cleaner'
  gem 'factory_girl'
  gem 'guard'
  gem 'guard-rspec'
  gem 'json_spec'
  gem 'pry'
  gem 'pry-byebug'
  gem 'reek'
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'simplecov'
end
